/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author mukws
 */
public class timetable extends javax.swing.JFrame {
    private Connection connection=null;
    private PreparedStatement ps=null;
    private ResultSet rs= null;
String radio=null;

    /**
     * Creates new form timetable
     */
    public timetable() {
        initComponents();
        connection=Database.dbConnect(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "null"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        button1 = new java.awt.Button();
        jFrame1 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        list2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ((javax.persistence.Query)null).getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roomno = new javax.swing.JTextField();
        build = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        radiolab = new javax.swing.JRadioButton();
        radioclass = new javax.swing.JRadioButton();
        btnadd = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        button1.setLabel("button1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD ROOM");
        setBackground(new java.awt.Color(0, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ROOMNO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 95, 90, 30));

        jLabel2.setText("BUILDING");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 151, 140, 20));

        jLabel3.setText("CAPACITY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 194, 140, 20));

        jLabel6.setText("ROOM TYPE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 20));

        roomno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roomno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnoActionPerformed(evt);
            }
        });
        getContentPane().add(roomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 280, 30));

        build.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        build.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildActionPerformed(evt);
            }
        });
        getContentPane().add(build, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 148, 278, 30));

        capacity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityActionPerformed(evt);
            }
        });
        getContentPane().add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 191, 280, 30));

        buttonGroup1.add(radiolab);
        radiolab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radiolab.setText("LAB");
        radiolab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiolab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiolabActionPerformed(evt);
            }
        });
        getContentPane().add(radiolab, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 120, -1));

        buttonGroup1.add(radioclass);
        radioclass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioclass.setText("CLASS");
        radioclass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioclassActionPerformed(evt);
            }
        });
        getContentPane().add(radioclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 126, -1));

        btnadd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnadd.setText("ADD ROOM");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 300, 60));

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(jFileChooser1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioclassActionPerformed

    private void capacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityActionPerformed
        // TODO add your handling code here:
        capacity.getText();
    }//GEN-LAST:event_capacityActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if(radiolab.isSelected()){
            radio="LAB";
        }
        else if(radioclass.isSelected()){
            radio="CLASS";
        }
        
        try {
             String sql="INSERT INTO classes(RoomNo, Building, Capacity, Room_Type) VALUES(?, ? , ? , ? ) ";
            ps=connection.prepareStatement(sql);
            ps.setString(1, roomno.getText());
            ps.setString(2, build.getText());
            ps.setString(3, capacity.getText());
            ps.setString(4,radio );
            JOptionPane.showMessageDialog(rootPane,"Data");
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Data is entered");
            System.out.println("winxdisd");
            
        /*    if(rs.next()){
                JOptionPane.showMessageDialog(rootPane,"Data is entered");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Data not entered");
            }
            */
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void roomnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnoActionPerformed
        // TODO add your handling code here:
        roomno.getText();
    }//GEN-LAST:event_roomnoActionPerformed

    private void buildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildActionPerformed
        // TODO add your handling code here:
        build.getText();
    }//GEN-LAST:event_buildActionPerformed

    private void radiolabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiolabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiolabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JTextField build;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField capacity;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.util.List list2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton radioclass;
    private javax.swing.JRadioButton radiolab;
    private javax.swing.JTextField roomno;
    // End of variables declaration//GEN-END:variables
}
